aditional/2-django/helloapp and todo/djangopractice/djangopractice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include("tasks.urls"))
]

aditional/2-django/helloapp and todo/djangopractice/helloapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.index, name="index"),
]

aditional/2-django/helloapp and todo/djangopractice/tasks/urls.py
from django.urls import path
from . import views

app_name = 'thetasksapp'

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

aditional/2-django/helloapp and todo/djangopractice/helloapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request, name = 'world'):
    return render(request, "hello/index.html", {
        "name": name.capitalize()
    })

aditional/2-django/helloapp and todo/djangopractice/tasks/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect


thetitle = "TODO App"

# Create your views here.
def index(request):
    # Check if there already exists a "tasks" key in our session

    if "tasks" not in request.session:

        # If not, create a new list
        request.session["tasks"] = ["t1", "t2", "t3"]

    return render(request, "tasks/index.html", {"tittleapp": thetitle,
        "tasks": request.session["tasks"]
    })



# Add a new task:
def add(request):
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = NewTaskForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            task = form.cleaned_data["task"]

            # Add the new task to our list of tasks
            request.session["tasks"] += [task]

            # Redirect user to list of tasks
            return HttpResponseRedirect(reverse("thetasksapp:index"))
        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

aditional/2-django/helloapp and todo/djangopractice/helloapp/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

aditional/2-django/helloapp and todo/djangopractice/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task:</h1>
    <form action="{% url 'thetasksapp:add' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
   <a href="{% url 'thetasksapp:index' %}">See tasks list</a>
{% endblock %}

aditional/2-django/helloapp and todo/djangopractice/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>{{ tittleapp }}</h1>
    <br>
    {% for task in tasks %}
        <li>{{ task }}</li>
    {% endfor %}
    <a href="{% url 'thetasksapp:add' %}">Add a New Task</a>
{% endblock %}

aditional/2-django/helloapp and todo/djangopractice/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% block body %}
    {% endblock %}
</body>

</html>